# TODO: Update this with your service name
service: example-service

frameworkVersion: '2'

plugins:
  - serverless-bundle

# Create an optimized package for each function
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

  # Define permission policies for this Lambda function
  iamRoleStatements:
    # Allow access to DynamoDb tables in eu-west-1
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

custom:
  # Stage setting passed through CLI, default: provider.stage
  deploymentStage: ${opt:stage, self:provider.stage}
  # Serverless-bundle webpack settings
  bundle:
    sourcemaps: true
    linting: false

functions:
# Defines HTTP API endpoints that call the handler function
  # POST /posts
  create:
    handler: create.handler
    events:
      - http:
          path: notes
          method: post
          cors: true
  # GET /notes
  get:
    handler: get.handler
    events:
      - http:
          path: notes
          method: get
          cors: true